version: '3'
services:
  db:
    image: mongo:3.6
    volumes:
     - dbroot:/data/db/
    ports:
     - "27017:27017"
  backend:
    image: alisopp/twitch_statistics:0.5
    volumes:
     - wwwroot:/wwwroot
    environment:
     - DB_PORT=27017
     - DB_HOST=db
     - DB_USERNAME=user
     - DB_PASSWORD=password
     - WWW_ROOT=/wwwroot/
     - DEBUG=False
     - START_DATE=01.01.2019
     - TWITCH_CREDENTIALS=1
  frontend:
    image: httpd:2.4
    ports:
     - "8080:80"
    volumes:
     - wwwroot:/usr/local/apache2/htdocs/
volumes:
  wwwroot:
  dbroot:
